# basic options
title: Frontmatters
author: justwebandsoftwaredevelopment
email: justwebandsoftwaredevelopment@gmail.com
description: Coding Site
twitter_username: justwebandsoftwaredevelopment1
github_username: justwebandsoftwaredevelopment

# build settings
markdown: kramdown
theme: minima
